/**
* Generated by go-doudou v2.0.1.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type DemoHandler interface {
	GetHealth(w http.ResponseWriter, r *http.Request)
}

func Routes(handler DemoHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "GetHealth",
			Method:      "GET",
			Pattern:     "/health",
			HandlerFunc: handler.GetHealth,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
