apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  serviceName: demo-svc-headless
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 6060
          name: http-port
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc-headless
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None