apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    a8r.io/bugs: "#21"
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: demo
        imagePullPolicy: Never
        name: demo
        ports:
        - containerPort: 6060
          name: http-port
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060