/**
* Generated by go-doudou v2.0.1.
* You can edit it as your need.
 */
package service

import "context"

//go:generate go-doudou svc http -c
//go:generate go-doudou svc grpc

type Demo interface {
	GetHealth(ctx context.Context) (status string, err error)
}
