/**
* Generated by go-doudou v2.0.1.
* You can edit it as your need.
 */
package service

import (
	"context"

	"github.com/wubin1989/bugtracker-controller/demo/config"
)

var _ Demo = (*DemoImpl)(nil)

type DemoImpl struct {
	conf *config.Config
}

func (receiver *DemoImpl) GetHealth(ctx context.Context) (status string, err error) {
	return "OK", nil
}

func NewDemo(conf *config.Config) *DemoImpl {
	return &DemoImpl{
		conf: conf,
	}
}
