/**
* Generated by go-doudou v2.0.1.
* You can edit it as your need.
 */
package main

import (
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
	service "github.com/wubin1989/bugtracker-controller/demo"
	"github.com/wubin1989/bugtracker-controller/demo/config"
	"github.com/wubin1989/bugtracker-controller/demo/transport/httpsrv"
)

func main() {
	conf := config.LoadFromEnv()
	svc := service.NewDemo(conf)
	handler := httpsrv.NewDemoHandler(svc)
	srv := rest.NewRestServer()
	srv.AddRoute(httpsrv.Routes(handler)...)
	srv.Run()
}
